services:
  - type: web
    name: quiz-app-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js

  - type: site
    name: quiz-ai-gwa
    buildCommand: cd client && npm install && npm run build
    publishPath: client/build
